# Trigger the pipeline on code changes to the master branch
trigger:
  branches:
    include:
      - development

# Define the pool of agents to run the pipeline jobs
pool:
  vmImage: 'ubuntu-latest'

# Define the build and deployment jobs
jobs:
  - job: 'Build'
    displayName: 'Build job'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build -- --configuration production
        displayName: 'Build the Angular app'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/dist/MyAngularApp.zip'
          replaceExistingArchive: true
        displayName: 'Create a zip file of the build artifacts'
  - job: 'Deploy'
    displayName: 'Deployment job'
    dependsOn: 'Build'
    condition: succeeded()
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              inputs:
                azureSubscription: '$(AzureSubscriptionName)'
                appName: '$(AppServiceName)'
                package: '$(Build.ArtifactStagingDirectory)/dist/MyAngularApp.zip'
                slotName: 'development'