trigger:
  branches:
    include:
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build the Angular app'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'Get-ChildItem "$(Build.BinariesDirectory)"'
    displayName: 'List contents of Build.BinariesDirectory'  


