trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build the Angular app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/MyAngularApp-$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Create a zip file of the build artifacts'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(AzureSubscriptionName)'
      appName: '$(AppServiceName)'
      package: '$(Build.ArtifactStagingDirectory)/MyAngularApp-$(Build.BuildId).zip'

